# Generated by Django 4.2.23 on 2025-06-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Unique stock ticker symbol (e.g., AAPL)', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, help_text='Company name', max_length=100)),
                ('exchange', models.CharField(blank=True, help_text='Stock exchange where the stock is listed', max_length=50)),
                ('country', models.CharField(blank=True, help_text='Country of the primary exchange', max_length=50)),
                ('currency', models.CharField(default='USD', help_text='Trading currency', max_length=3)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('ETF', 'ETF'), ('INDEX', 'Index'), ('CRYPTO', 'Cryptocurrency'), ('OTHER', 'Other')], default='STOCK', help_text='Type of financial instrument', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the stock is currently active/traded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='scrape_stoc_symbol_4483c3_idx'), models.Index(fields=['exchange'], name='scrape_stoc_exchang_d75d78_idx')],
            },
        ),
    ]
