# Generated by Django 4.2.23 on 2025-06-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='checksum',
            field=models.CharField(default='', max_length=128),
        ),
    ]
