# Generated by Django 4.2.23 on 2025-06-22 08:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrape_stock_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('high', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('low', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('close', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('adj_close', models.DecimalField(blank=True, decimal_places=3, help_text='Adjusted close price for corporate actions', max_digits=12, null=True)),
                ('volume', models.BigIntegerField(help_text='Number of shares traded', validators=[django.core.validators.MinValueValidator(0)])),
                ('change_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Percentage change from previous close', max_digits=7, null=True)),
                ('data_source', models.CharField(default='Yahoo Finance', max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='scrape_stock_list.stocklist')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='scrape_pric_stock_i_434632_idx'), models.Index(fields=['date'], name='scrape_pric_date_81c8e3_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
